### ISSUE TITLE
add a `replacing = 'xxx'` field for tools in the toolset manifest

### ISSUE THREAD

**Issue by J-ZhengLi** [J-ZhengLi/rim#196]
Demo:

```toml
# in toolset_manifest.toml
[tools.target.x86_64-pc-windows-msvc]
# old_tool = "0.1.0" # deprecated
new_tool = { ver = "1.0.0", replacing = "old_tool" }
```

Then, when installing `new_tool`, program should try uninstalling `old_tool` first before installing `new_tool` after user's confirmation
